### ISSUE TITLE
关于博客排版和评论授权的吐槽

### ISSUE THREAD

**Issue by xymoryn** [Mabbs/mabbs.github.io#167]
## 关于评论权限

本来要发在 [最近对博客搜索功能的优化记录 | Mayx的博客](https://mabbs.github.io/2025/04/04/search.html) 的，结果评论时发现关联 GitHub 请求的权限太高了。

哪有评论一下就要读者给所有公开仓库的读写权限的😂

![Image](https://github.com/user-attachments/assets/b460dc80-9715-4e29-a070-e1c90cc6088d)

---

## 关于文章排版

有些排版问题挺影响阅读体验。

![Image](https://github.com/user-attachments/assets/2f0fa3ed-94e2-4f6f-ac52-65aa1a312494)

### 分区

左侧的 header 占了内容区域近三分之一的宽度，正文相当局促，阅读时容易分散注意力。

### 分段

多个段落挤在一个 p 标签用 br 分隔，文字一长区分不明显。

看了下 Markdown 原文，应该是换行方式导致的。Markdown 里，行末加两个空格只会插入 br，用空行分隔才会创建段落。

### 语义和样式

一些区块（如目录、标签），没有明确的语义，可以考虑用类名等方式加上。

一些区块（如统计数据、标签），通过 small 标签来缩小文本，把语义和样式混合在一起，容易给 CSS 的应用带来麻烦。

---

顺带一提，文章里提到的右侧链接，可以用 `display:flex` 来替代 `float:right`,兼容性更好。

**原**

```html
<small style="display: block;">
  tags: 
  <a href="xxx"><em>博客</em></a> - 
  <a href="xxx"><em>搜索</em></a> - 
  <a href="xxx"><em>优化</em></a>
  <span style="float: right;">
    <a href="xxx">查看原始文件</a>
  </span>
</small>
```

**修改**

```html
<small style="display: flex; justify-content: space-between; align-items: center;">
  <span>
    tags: 
    <a href="xxx"><em>博客</em></a> - 
    <a href="xxx"><em>搜索</em></a> - 
    <a href="xxx"><em>优化</em></a>
  </span>
  <span>
    <a href="xxx">查看原始文件</a>
  </span>
</small>
```

**Comment by xymoryn** [comment]
之前还让 AI 写过美化样式，博主也可以参考看看。

<details>
<summary>Stylus 样式</summary>

```css
/* ==UserStyle==
@name           Mayx的博客
@namespace      github.com/openstyles/stylus
@version        0.0.1
@description    A new userstyle
@author         Me
==/UserStyle== */
@-moz-document domain("mabbs.github.io") {
	/* =============================
           🎨 变量定义：Catppuccin 配色
        ============================= */
	:root {
		/* Latte theme colors */
		--latte-rosewater: #e0a498;
		--latte-flamingo: #e08a8a;
		--latte-pink: #e68abe;
		--latte-mauve: #9a5cef;
		--latte-red: #d83a51;
		--latte-maroon: #e06b76;
		--latte-peach: #e67e3b;
		--latte-yellow: #d9a044;
		--latte-green: #60b050;
		--latte-teal: #45a0a5;
		--latte-sky: #52aed8;
		--latte-sapphire: #4ca6b8;
		--latte-blue: #4a7dd0;
		--latte-lavender: #8c99e3;
		--latte-text: #4c4f69;
		--latte-subtext1: #5c5f77;
		--latte-subtext0: #6c6f85;
		--latte-overlay2: #7c7f93;
		--latte-overlay1: #8c8fa1;
		--latte-overlay0: #9ca0b0;
		--latte-surface2: #acb0be;
		--latte-surface1: #bcc0cc;
		--latte-surface0: #d5d9e3;
		--latte-base: #f5f7fa;
		--latte-mantle: #eaecf2;
		--latte-crust: #e0e4ec;

		/* Mocha theme colors */
		--mocha-rosewater: #f5e0dc;
		--mocha-flamingo: #f2cdcd;
		--mocha-pink: #f5c2e7;
		--mocha-mauve: #d4b6f9;
		--mocha-red: #f5a3b8;
		--mocha-maroon: #edb0b9;
		--mocha-peach: #f8c4a2;
		--mocha-yellow: #f9e5b8;
		--mocha-green: #b7e3b4;
		--mocha-teal: #a6e6db;
		--mocha-sky: #a0e2ee;
		--mocha-sapphire: #8cd0ed;
		--mocha-blue: #a1c2f5;
		--mocha-lavender: #c1c9fa;
		--mocha-text: #d8e0f7;
		--mocha-subtext1: #bac2de;
		--mocha-subtext0: #a6adc8;
		--mocha-overlay2: #9399b2;
		--mocha-overlay1: #7f849c;
		--mocha-overlay0: #6c7086;
		--mocha-surface2: #585b70;
		--mocha-surface1: #45475a;
		--mocha-surface0: #363852;
		--mocha-base: #282838;
		--mocha-mantle: #212130;
		--mocha-crust: #191922;
	}

	/* Theme variables */
	@media (prefers-color-scheme: light) {
		:root {
			--primary-color: var(--latte-text);
			--background-color: var(--latte-base);
			--heading-color: var(--latte-mauve);
			--link-color: var(--latte-blue);
			--blockquote-bg: var(--latte-surface0);
			--blockquote-border: var(--latte-lavender);
			--blockquote-text: var(--latte-subtext1);
			--code-bg: var(--latte-surface0);
			--code-border: var(--latte-surface1);
			--table-border: var(--latte-surface2);
			--table-header-bg: var(--latte-surface0);
			--hr-color: var(--latte-surface2);
			--del-color: var(--latte-overlay1);
			--selection-bg: var(--latte-lavender);
			--selection-text: var(--latte-base);
		}
	}

	@media (prefers-color-scheme: dark) {
		:root {
			--primary-color: var(--mocha-text);
			--background-color: var(--mocha-base);
			--heading-color: var(--mocha-mauve);
			--link-color: var(--mocha-blue);
			--blockquote-bg: var(--mocha-surface0);
			--blockquote-border: var(--mocha-lavender);
			--blockquote-text: var(--mocha-subtext1);
			--code-bg: var(--mocha-subtext0);
			--code-border: var(--mocha-surface1);
			--table-border: var(--mocha-surface2);
			--table-header-bg: var(--mocha-surface0);
			--hr-color: var(--mocha-surface2);
			--del-color: var(--mocha-overlay1);
			--selection-bg: var(--mocha-lavender);
			--selection-text: var(--mocha-base);
		}
	}

	/* =============================
           🧱 页面布局结构
        ============================= */
	html,
	body {
		height: 100%;
		margin: 0;
	}

	body {
		font-family: 'Sarasa UI SC', 'Source Han Sans CN', 'Noto Sans CJK SC', 'PingFang SC',
		'Microsoft YaHei', 'Hiragino Sans GB', 'WenQuanYi Micro Hei', 'Droid Sans Fallback', system-ui,
		Arial, sans-serif;
		font-size: 16px;
		line-height: 1.6;
		color: var(--primary-color);
		background-color: var(--background-color);
		/* 两端对齐 */
		text-align: justify;
		text-justify: inter-character;
		text-rendering: optimizeLegibility;
		/* 换行 */
		overflow-wrap: break-word;
		hyphens: auto;
		line-break: strict;
	}

	.wrapper {
		display: grid;
		grid-template-rows: auto 1fr auto;
		min-height: 100%;
		max-width: 700px;
		margin: 0 auto;
		padding: 0 20px;
	}

	header,
	footer {
		position: static;
	}

	section {
		width: auto;
	}

	/* 隐藏看板娘和 AI 摘要 */
	#landlord,
	#ai-output,
	section > hr:first-of-type,
	section > b:first-of-type {
		display: none !important;
	}

	/* =============================
           ✨ 内容样式优化
        ============================= */
	/* 标题 */
	h1,
	h2,
	h3,
	h4,
	h5,
	h6 {
		margin-top: 1.5em;
		margin-bottom: 0.5em;
		color: var(--heading-color);
		font-weight: 600;
	}

	/* 模拟段落换行 */
	br {
		content: '';
		display: block;
		margin-block: 0.6em;
	}

	/* 链接 */
	a {
		color: var(--link-color);
		text-decoration: none;
	}
	a:hover {
		text-decoration: underline;
		/* 避免原样式的字体加粗导致文本换行 */
		font-weight: normal;
	}

	/* 引用 */
	blockquote {
		margin: 1em 0;
		padding: 0.5em 1em;
		border-left: 4px solid var(--blockquote-border);
		background-color: var(--blockquote-bg);
		color: var(--blockquote-text);
	}

	/* 图片 */
	img {
		max-width: 100%;
		height: auto;
		display: block;
		margin: 1em auto;
	}

	/* 
    代码块
    自动换行
    限制最大高度
  */
	code,
	pre {
		font-family: 'Sarasa Mono SC', 'Source Han Mono SC', 'Noto Sans Mono CJK SC', ui-monospace,
		'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace;
		background-color: var(--code-bg) !important;
	}

	code {
		padding: 2px 4px;
		border-radius: 3px;
		white-space: pre-wrap;
		word-break: break-all;
		overflow-x: auto;
	}

	pre {
		white-space: pre;
		max-width: 100%;
		max-height: 500px;
		overflow: auto;
		border: 1px solid var(--code-border);
		padding: 10px;
		border-radius: 6px;
	}

	/* 列表样式 */
	ul,
	ol {
		padding-left: 2em;
		margin-bottom: 1em;
	}

	li {
		margin-bottom: 0.5em;
	}

	/* 表格样式 */
	table {
		border-collapse: collapse;
		width: 100%;
		margin-bottom: 1em;
	}

	th,
	td {
		border: 1px solid var(--table-border);
		padding: 8px;
		text-align: left;
	}

	th {
		background-color: var(--table-header-bg);
		font-weight: bold;
	}

	/* 水平线样式 */
	hr {
		border: none;
		border-top: 1px solid var(--hr-color);
		margin: 2em 0;
	}

	/* 删除线文本样式 */
	del {
		text-decoration: line-through;
		color: var(--del-color);
	}

	/* 上标和下标样式 */
	sup,
	sub {
		font-size: 75%;
		line-height: 0;
		position: relative;
		vertical-align: baseline;
	}

	sup {
		top: -0.5em;
	}

	sub {
		bottom: -0.25em;
	}

	/* 文本选中效果 */
	::selection {
		background-color: var(--selection-bg);
		color: var(--selection-text);
		text-shadow: none;
	}

	/* =============================
           📱 响应式样式（大屏优化）
        ============================= */
	@media (min-width: 768px) {
		.wrapper {
			letter-spacing: 0.05em;
		}
	}
}
```

</details>

![Image](https://github.com/user-attachments/assets/7d9e9108-04f5-4bda-b8b2-265e1946b887)

![Image](https://github.com/user-attachments/assets/db204f2d-49bc-42f4-a7b4-3efbd7a05a4a)

**Comment by Mabbs** [comment]
感谢你的建议，首先关于评论权限的问题主要是我用的Gitalk项目有点老，而且停更了，只支持这种授权🥲
https://github.com/gitalk/gitalk/issues/95
本来想试试giscus的，但是发现它需要后端，而且它的授权看起来比gitalk的授权还广泛，如果直接接官网的我会很不放心……
至于其他评论系统，感觉都不如接到GitHub上省心

---

关于页面布局和样式，我是直接套的 http://github.com/pages-themes/minimal 
不过对我个人来说，我还是比较喜欢左右结构的布局，不然我就选择其他主题了😆
当然段落确实是有些问题，只是我刚建博客的时候还不知道markdown怎么分段，只是要修改的话所有文章都得更新，后续我考虑一下怎么解决。
对于html语义之类的……我感觉能用就行（其实关于那个右侧链接我也问过我的前端朋友，他也推荐flex，但是说改的地方比较多，所以我嫌麻烦就没用这个😝）

---

> 之前还让 AI 写过美化样式，博主也可以参考看看。
> 
> Stylus 样式
> ![Image](https://github.com/user-attachments/assets/7d9e9108-04f5-4bda-b8b2-265e1946b887)
> 
> ![Image](https://github.com/user-attachments/assets/db204f2d-49bc-42f4-a7b4-3efbd7a05a4a)

关于这个样式我试了一下，效果还是有些欠缺，另外也不太符合我的风格

<img width="228" alt="Image" src="https://github.com/user-attachments/assets/f47e7210-fc59-43ee-a0f4-7b5dd8a4804d" />

不过确实字有些密，我回头看看怎么写个样式（不过我对css不太熟😭）

我会再考虑一下如何对我的博客进行修改，十分感谢

**Comment by xymoryn** [comment]
> 本来想试试giscus的，但是发现它需要后端，而且它的授权看起来比gitalk的授权还广泛，如果直接接官网的我会很不放心……

看了下 Giscus 的 [自托管文档](https://github.com/giscus/giscus/blob/main/SELF-HOSTING.md#repository-permissions)，只需要评论仓库的讨论区读写权限，应该还好吧？

![Image](https://github.com/user-attachments/assets/92f28879-b02f-43ee-8f36-9e8a8194da79)

---

> 只是我刚建博客的时候还不知道markdown怎么分段，只是要修改的话所有文章都得更新，后续我考虑一下怎么解决。

简单写了个正则匹配，看着大部分文章都可以直接替换，就是有些代码和特殊样式可能要排除下。

![Image](https://github.com/user-attachments/assets/8123e62b-a4b0-4e24-a881-18476e77b4d7)

![Image](https://github.com/user-attachments/assets/6cdba933-09e1-460a-8e5d-97d66ad71189)

---

排版的话，主要是博客现在的正文区域、文字大小和间距都比较小，读着有点费劲。

像前面的样式，真正重要只有下面这部分。

<details>
<summary>Details</summary>

```css
body {
  font-size: 16px;
  line-height: 1.6;
  /* 两端对齐 */
  text-align: justify;
  text-justify: inter-character;
  text-rendering: optimizeLegibility;
  /* 换行 */
  overflow-wrap: break-word;
  hyphens: auto;
  line-break: strict;
}

/* 改成上下分区 */
.wrapper {
  display: grid;
  grid-template-rows: auto 1fr auto;
  min-height: 100%;
  max-width: 700px;
  margin: 0 auto;
  padding: 0 20px;
}

header,
footer {
  position: static;
}

section {
  width: auto;
}

/* 模拟段落换行 */
br {
  content: '';
  display: block;
  margin-block: 0.6em;
}

a:hover {
  text-decoration: underline;
  /* 避免原链接样式鼠标悬停时，字体加粗导致文本换行 */
  font-weight: normal;
}

/* 
  代码块
  自动换行
  限制最大高度
*/
code {
  white-space: pre-wrap;
  word-break: break-all;
  overflow-x: auto;
}

pre {
  white-space: pre;
  max-height: 500px;
  overflow: auto;
}

```

</details>
